title: ALUMINUMOS BY MORTCODESWEB
description: AluminumOS is an operating system designed for simplicity, ease of use, customizability, and control. It has no tracking or ads and can be downloaded free anytime you want in any device and any type of architecture... The best part is it's open source!
baseurl: index.html
theme: slate
